# Generated by Django 2.1.5 on 2019-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tweet_body', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_retweet', models.BooleanField(default=False)),
                ('retweets', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
