# Generated by Django 2.1.5 on 2019-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_body',
            new_name='tweet_text',
        ),
    ]
