# Generated by Django 2.1.5 on 2019-01-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20190111_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.User'),
        ),
    ]
